config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'products#index'

  mount API::Base => '/api'

  devise_for :users
  resources :users do
    resources :receivers
  end

  resources :orders do
    member do
      patch  'delivery'
      delete 'cancel'
    end
  end
  resources :products

  resource :cart, only:[:show, :destroy] do
    collection do
      post :add, path:'add/:id'
    end
  end

end

app/models/receiver.rb
class Receiver < ApplicationRecord
  belongs_to :user, :class_name => "User", :foreign_key => :user_id
  has_many :orders
end

app/controllers/receivers_controller.rb
class ReceiversController < ApplicationController
  before_action :member_required
  before_action :set_user
  before_action :set_receiver, only: [:show, :edit, :update, :destroy]

  # GET /receivers
  # GET /receivers.json
  def index
    @receivers = Receiver.all
  end

  # GET /receivers/1
  # GET /receivers/1.json
  def show
  end

  # GET /receivers/new
  def new
    @receiver = Receiver.new
  end

  # GET /receivers/1/edit
  def edit
  end

  # POST /receivers
  # POST /receivers.json
  def create
    @receiver = current_user.receivers.new(receiver_params)

    respond_to do |format|
      if @receiver.save
        format.html { redirect_to @user, notice: 'Receiver was successfully created.' }
        format.json { render :show, status: :created, location: @receiver }
      else
        format.html { render :new }
        format.json { render json: @receiver.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /receivers/1
  # PATCH/PUT /receivers/1.json
  def update
    respond_to do |format|
      if @receiver.update(receiver_params)
        format.html { redirect_to @user, notice: 'Receiver was successfully updated.' }
        format.json { render :show, status: :ok, location: @receiver }
      else
        format.html { render :edit }
        format.json { render json: @receiver.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /receivers/1
  # DELETE /receivers/1.json
  def destroy
    if not is_self?
      return
    end

    @receiver.destroy
    respond_to do |format|
      format.html { redirect_to @user, notice: 'Receiver was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_receiver
      @receiver = current_user.receivers.find(params[:id])
    end

    def set_user
      @user = User.find(params[:user_id])
    end

    def is_self?
      current_user.id == @user.id
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def receiver_params
      params.require(:receiver).permit(:name, :phone, :address)
    end
end

app/helpers/receivers_helper.rb
module ReceiversHelper
end

app/views/receivers/_form.html.erb
<% url = "new" == action_name ? user_receivers_path(@user.id) : user_receiver_path(@user.id, receiver.id) %>
<%= form_with(model: receiver, local:true, url: url) do |form| %>
  <% if receiver.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(receiver.errors.count, "error") %> prohibited this receiver from being saved:</h2>

      <ul>
      <% receiver.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :receiver_name %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone, id: :receiver_phone %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :receiver_address %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/receivers/edit.html.erb
<h1>Editing Receiver</h1>

<%= render 'form', receiver: @receiver %>

<%= link_to 'Back', user_path(@user) %>

app/views/receivers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Receivers</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Name</th>
      <th>Phone</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @receivers.each do |receiver| %>
      <tr>
        <td><%= receiver.user_id %></td>
        <td><%= receiver.name %></td>
        <td><%= receiver.phone %></td>
        <td><%= receiver.address %></td>
        <td><%= link_to 'Show', receiver %></td>
        <td><%= link_to 'Edit', edit_receiver_path(receiver) %></td>
        <td><%= link_to 'Destroy', receiver, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Receiver', new_receiver_path %>

app/views/receivers/new.html.erb
<h1>New Receiver</h1>

<%= render 'form', receiver: @receiver %>

<%= link_to 'Back', user_path(@user.id) %>

app/views/receivers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @receiver.user_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @receiver.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @receiver.phone %>
</p>

<p>
  <strong>Address:</strong>
  <%= @receiver.address %>
</p>

<%= link_to 'Edit', edit_receiver_path(@receiver) %> |
<%= link_to 'Back', receivers_path %>