config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'products#index'

  mount API::Base => '/api'

  devise_for :users
  resources :users do
    resources :receivers
  end

  resources :orders do
    member do
      patch  'delivery'
      delete 'cancel'
    end
  end
  resources :products

  resource :cart, only:[:show, :destroy] do
    collection do
      post :add, path:'add/:id'
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :receivers

  before_save :ensure_access_token

  def is_admin?
    100 <= self.role
  end

  def ensure_access_token
    self.access_token ||= generate_access_token
  end

  def generate_access_token
    loop do
      token = Devise.friendly_token
      break token unless User.where(access_token: token).first
    end
  end

  def as_sign_in_json
    self.as_json(
      only: [:id, :email, :name, :role, :access_token]
    )
  end
end

app/controllers/api/v1/users.rb
module API
  module V1
    class Users < Grape::API
      include API::V1::Defaults

      resource :users do
        # POST /api/v1/users/sign_in
        # Role: anonymous
        # 登入
        desc "Sign in"
        params do
          requires :email, type: String, regexp: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i, desc: "User email"
          requires :password, type: String, desc: "User password"
        end
        post :sign_in do
          email = params[:email]
          password = params[:password]

          error!('400 email and password missing.', 400) if email.nil? || password.nil?

          user = User.find_by(email: email.downcase)

          error!('404 email not found.', 404) if user.nil?
          error!('403 password not match.', 403) if !user.valid_password?(password)

          user.ensure_access_token
          user.save
          status(201)
          envelope(user.as_sign_in_json)
        end
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :member_required, only: [:show, :edit, :update, :destroy]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'user was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name)
    end
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(users.errors.count, "error") %> prohibited this users from being saved:</h2>

      <ul>
      <% users.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :users_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>編輯使用者</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', user_path(@user.id) %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h3>個人資料</h3>
<ul>
  <li>Email: <%= @user.email %></li>
  <li>Name: <%= @user.name %></li>
</ul>
<%= link_to '編輯個人資料', edit_user_path(@user.id), class: 'btn btn-primary btn-xs' %>


<h3>收件人資訊</h3>
<%= link_to '新增收件人資訊', new_user_receiver_path(@user.id), class: 'btn btn-primary btn-xs' %>
<ul>
<% @user.receivers.each do |receiver| %>
  <li>
    <div>姓名: <%= receiver.name %></div>
    <div>電話：<%= receiver.phone %></div>
    <div>地址：<%= receiver.address %></div>
    <div>
      <%= link_to '編輯', edit_user_receiver_path(@user.id, receiver.id), class: 'btn btn-info btn-xs' %>
      <%= link_to '刪除', user_receiver_path(@user.id, receiver.id), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' %>
    </div>

  </li>
<% end %>
</ul>

<h3>訂單列表</h3>
<ul>
<% @user.receivers.each do |receiver| %>
  <% receiver.orders.each do |order| %>
  <li>
    <h4>訂單編號 <%= order.id%> (<%= order.status_name%> <%= order.payment_name %>)</h4>
    <h5>訂單內容</h5>
    <div>
    <% order.order_products.each do |item| %>
      <p><%= item.product.name %> <%= number_to_currency(item.pricing, precision: 0) %>元 X <%= item.amount %>件</p>
    <% end %>
    </div>
    <h5>收件人資訊</h5>
    <div>
      <%= order.receiver.name %> <%= order.receiver.phone %> <%= order.receiver.address %>
    </div>
  </li>
  <% end %>
<% end %>
</ul>