config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'products#index'

  mount API::Base => '/api'

  devise_for :users
  resources :users do
    resources :receivers
  end

  resources :orders do
    member do
      patch  'delivery'
      delete 'cancel'
    end
  end
  resources :products

  resource :cart, only:[:show, :destroy] do
    collection do
      post :add, path:'add/:id'
    end
  end

end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/api/v1/products.rb
module API
  module V1
    class Products < Grape::API
      include API::V1::Defaults

      resource :products do
        # GET /api/v1/products
        # Role: anonymous
        # 商品列表
        desc "Products list"
        params do
        end
        get do
          products = Product.all

          status(200)
          envelope(products)
        end
      end
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :admin_required, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :pricing, :descriptions)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :product_name %>
  </div>

  <div class="field">
    <%= form.label :pricing %>
    <%= form.text_field :pricing, id: :product_pricing %>
  </div>

  <div class="field">
    <%= form.label :descriptions %>
    <%= form.text_area :descriptions, id: :product_descriptions %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>商品列表</h1>

<div class="row">
<% @products.each do |product| %>
  <div class="col-xs-6">
    <div class="row">
      <a href="<%= product_path(product) %>">
        <h3><%= product.name %></h3>
        <h5><%= number_to_currency(product.pricing, precision: 0) %></h5>
        <p><%= product.descriptions %></p>
      </a>
      <%= link_to '加到購物車', add_cart_path(product), method: "post", class: "btn btn-xs btn-danger" %>
    </div>
  </div>
<% end %>
</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<%= link_to '回到列表', products_path %>

<p id="notice"><%= notice %></p>

<h3><%= @product.name %></h3>
<h5><%= number_to_currency(@product.pricing, precision: 0) %></h5>
<p><%= @product.descriptions %></p>

<%= link_to '加到購物車', add_cart_path(@product), method: "post", class: "btn btn-xs btn-danger" %>